Algoritmo "SSMD"

Var
n1, n2, soma, subt, mult, divi:real


Inicio
escreval("Digite o primeiro número:")
leia(n1)
escreval("Digite o segundo número")
leia(n2)
limpatela
soma<-n1+n2
subt<-n1-n2
mult<-n1*n2
divi<-n1/n2
escreval("A soma entre ",n1," e ",n2," é igual a ",soma)
escreval("A subtração entre ",n1," e ",n2," é igual a",subt)
escreval("A multiplicação entre ",n1," e ",n2," é igual a",mult)
escreval("A divisão entre ",n1," e ",n2," é igual a ",divi)

Fimalgoritmo